#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonDataImporter
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yelp")]
	public partial class BusinessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbusiness(business instance);
    partial void Updatebusiness(business instance);
    partial void Deletebusiness(business instance);
    partial void Insertbusiness_category(business_category instance);
    partial void Updatebusiness_category(business_category instance);
    partial void Deletebusiness_category(business_category instance);
    #endregion
		
		public BusinessDataContext() : 
				base(global::JsonDataImporter.Properties.Settings.Default.yelpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BusinessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BusinessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BusinessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BusinessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<business> businesses
		{
			get
			{
				return this.GetTable<business>();
			}
		}
		
		public System.Data.Linq.Table<business_category> business_categories
		{
			get
			{
				return this.GetTable<business_category>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.business")]
	public partial class business : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _business_id;
		
		private string _full_address;
		
		private System.Nullable<bool> _open;
		
		private string _city;
		
		private System.Nullable<int> _review_count;
		
		private string _name;
		
		private string _state;
		
		private System.Nullable<decimal> _stars;
		
		private string _type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbusiness_idChanging(string value);
    partial void Onbusiness_idChanged();
    partial void Onfull_addressChanging(string value);
    partial void Onfull_addressChanged();
    partial void OnopenChanging(System.Nullable<bool> value);
    partial void OnopenChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void Onreview_countChanging(System.Nullable<int> value);
    partial void Onreview_countChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnstarsChanging(System.Nullable<decimal> value);
    partial void OnstarsChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public business()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business_id", DbType="NChar(22) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string business_id
		{
			get
			{
				return this._business_id;
			}
			set
			{
				if ((this._business_id != value))
				{
					this.Onbusiness_idChanging(value);
					this.SendPropertyChanging();
					this._business_id = value;
					this.SendPropertyChanged("business_id");
					this.Onbusiness_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_address", DbType="NVarChar(200)")]
		public string full_address
		{
			get
			{
				return this._full_address;
			}
			set
			{
				if ((this._full_address != value))
				{
					this.Onfull_addressChanging(value);
					this.SendPropertyChanging();
					this._full_address = value;
					this.SendPropertyChanged("full_address");
					this.Onfull_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[open]", Storage="_open", DbType="Bit")]
		public System.Nullable<bool> open
		{
			get
			{
				return this._open;
			}
			set
			{
				if ((this._open != value))
				{
					this.OnopenChanging(value);
					this.SendPropertyChanging();
					this._open = value;
					this.SendPropertyChanged("open");
					this.OnopenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_review_count", DbType="Int")]
		public System.Nullable<int> review_count
		{
			get
			{
				return this._review_count;
			}
			set
			{
				if ((this._review_count != value))
				{
					this.Onreview_countChanging(value);
					this.SendPropertyChanging();
					this._review_count = value;
					this.SendPropertyChanged("review_count");
					this.Onreview_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(10)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stars", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> stars
		{
			get
			{
				return this._stars;
			}
			set
			{
				if ((this._stars != value))
				{
					this.OnstarsChanging(value);
					this.SendPropertyChanging();
					this._stars = value;
					this.SendPropertyChanged("stars");
					this.OnstarsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(20)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.business_category")]
	public partial class business_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _business_category_id;
		
		private string _business_id;
		
		private string _category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbusiness_category_idChanging(long value);
    partial void Onbusiness_category_idChanged();
    partial void Onbusiness_idChanging(string value);
    partial void Onbusiness_idChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    #endregion
		
		public business_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business_category_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long business_category_id
		{
			get
			{
				return this._business_category_id;
			}
			set
			{
				if ((this._business_category_id != value))
				{
					this.Onbusiness_category_idChanging(value);
					this.SendPropertyChanging();
					this._business_category_id = value;
					this.SendPropertyChanged("business_category_id");
					this.Onbusiness_category_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business_id", DbType="NVarChar(22) NOT NULL", CanBeNull=false)]
		public string business_id
		{
			get
			{
				return this._business_id;
			}
			set
			{
				if ((this._business_id != value))
				{
					this.Onbusiness_idChanging(value);
					this.SendPropertyChanging();
					this._business_id = value;
					this.SendPropertyChanged("business_id");
					this.Onbusiness_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(100)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
